VOCABULARY_FILE=$1
OUTPUT_WORD_NGRAMS=$2
OUTPUT_NGRAM_INFO_FILE=$3

./get_ngrams.pl ${VOCABULARY_FILE} ${OUTPUT_WORD_NGRAMS} ${OUTPUT_NGRAM_INFO_FILE};
sort -t$'\t' -nr -k3,3 ${OUTPUT_NGRAM_INFO_FILE} -o ${OUTPUT_NGRAM_INFO_FILE};
LC_ALL=c sort -t$'\t' -k1,1 ${OUTPUT_WORD_NGRAMS} -o ${OUTPUT_WORD_NGRAMS};
